"""Add price column to Flight model

Revision ID: 621c48ce80b5
Revises: 76bb7e7f5770
Create Date: 2024-12-06 22:37:03.085692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621c48ce80b5'
down_revision = '76bb7e7f5770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
