"""update airport attrs

Revision ID: f41df0d33774
Revises: a2fcb6cf5048
Create Date: 2024-12-07 02:11:14.175630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41df0d33774'
down_revision = 'a2fcb6cf5048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airport_id_icao', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_column('airport_id_icao')

    # ### end Alembic commands ###
