"""Add ICAO fields to Flight model

Revision ID: ffd2f6de8b14
Revises: c14e35086c45
Create Date: 2024-12-07 00:22:25.695399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd2f6de8b14'
down_revision = 'c14e35086c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airline_id', sa.String(length=10), nullable=True))
        batch_op.alter_column('origin',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('destination',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('origin',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('airline_id')

    # ### end Alembic commands ###
